[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pgvector>=0.3.6",
    "sentence-transformers>=3.3.1",
]
