name: Build and deploy container app to Azure Web App - GYMAIEngine

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Give us permission to push images to GHCR
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # (Optional) Log in to GHCR using GitHub Actions token
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Pass in the Font Awesome token from GitHub Secrets
          build-args: |
            FONTAWESOME_TOKEN=${{ secrets.FONTAWESOME_TOKEN }}
          tags: ghcr.io/mahluminnovationsllc/chatbot-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'GYMAIEngine'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_62085907b7c1484bb409457265784452 }}
          images: 'ghcr.io/mahluminnovationsllc/chatbot-app:${{ github.sha }}'